# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

en:
  languageCode: en
  title: Alphabiz Official Website
  contentDir: content/en

zh:
  languageCode: zh
  title: Alphabiz 中文官网
  contentDir: content/zh
