# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: menu_item_home
    url: /
    weight: 10

  - name: menu_item_blog
    url: blog/
    weight: 20

  - name: menu_item_download
    url: 'https://github.com/tanshuai/alphabiz/releases'
    weight: 50

  - name: menu_item_docs
    url: 'https://github.com/tanshuai/alphabiz/wiki'
    weight: 60

  - name: menu_item_support
    url: 'https://github.com/tanshuai/alphabiz/issues'
    weight: 70

  - name: menu_item_community
    url: 'https://github.com/tanshuai/alphabiz/discussions'
    weight: 80

  - name: menu_item_about
    url: about/
    weight: 100
