footer:
  text: '一段页脚静态文本'
copyright:
  notice: '© {year} wowchemy prototype. 版权所有'


# Localization
locale:
  date_format: '2006 Jan 2'

########################################################################################################################
