# Localization
locale:
  date_format: 'Jan 2, 2006'

# Site footer
footer:
  text: 'a footer static text'
copyright:
  notice: '© {year} wowchemy prototype. All Rights Reserved'
#  license:
#    enable: true
#    allow_commercial: false
#    allow_derivatives: false
#    share_alike: true
