copyright:
  notice: 'Copyright ©{year} Alphabiz. All Rights Reserved.'

# Localization
locale:
  date_format: '2006年1月2日'

########################################################################################################################
